# Generated by Django 5.1.5 on 2025-01-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zlauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchamodel",
            name="eamil",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
