# Generated by Django 5.1.5 on 2025-01-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zlauth", "0002_alter_captchamodel_eamil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="captchamodel",
            old_name="eamil",
            new_name="email",
        ),
    ]
